"""create tables

Revision ID: 01629407d7ff
Revises: 89e4c188ed68
Create Date: 2023-12-19 01:52:42.259845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01629407d7ff'
down_revision: Union[str, None] = '89e4c188ed68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('happiness_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'happiness_score')
    # ### end Alembic commands ###
