"""create tables

Revision ID: d1de466cf311
Revises: 38f83bd742c8
Create Date: 2023-12-21 06:36:17.519494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1de466cf311'
down_revision: Union[str, None] = '38f83bd742c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('sadness_score', sa.Integer(), nullable=True))
    op.add_column('patients', sa.Column('favorite_tv_show', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'favorite_tv_show')
    op.drop_column('patients', 'sadness_score')
    # ### end Alembic commands ###
